# Generated by Django 6.0.1 on 2026-01-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_avatar_remove_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_nick",
            field=models.CharField(
                help_text="Введите свой телеграм ник",
                max_length=50,
                null=True,
                verbose_name="Телеграм ник",
            ),
        ),
    ]
